### ISSUE TITLE
Hello, can we share data files? I am no longer able to access it on the Kaggle website

### ISSUE THREAD

**Issue by shuzhiY** [Han-Yuan-Med/template-explanation#1]
Hello, can we share data files? I am no longer able to access it on the Kaggle website

**Comment by shuzhiY** [comment]
Hello, can the Symbolic_overlap_15. png and related D: \ \ SIIM-ACR Dataset \ \ masks in the code be shared? I am very interested in templates. I'd be glad if you could help me.

**Comment by Han-Yuan-Med** [comment]
> Hello, can the Symbolic_overlap_15. png and related D: \ \ SIIM-ACR Dataset \ \ masks in the code be shared? I am very interested in templates. I'd be glad if you could help me.

Hi, I cannot retrieve the original files since I have left academia. While I do find some figures that may be the candidate templates for your reference. For the original dataset, maybe you can request from some other authors with access to it.
![Symbolic_mask_6](https://github.com/user-attachments/assets/5a257283-6a67-41a1-b4c5-be72f032b3c5)
![Symbolic_mask_3](https://github.com/user-attachments/assets/3f02ec02-66de-49d5-bd12-b24989d9b6e8)
![Symbolic_mask_4](https://github.com/user-attachments/assets/9c26ec65-172b-401a-af3e-98d3c580e974)
![Symbolic_mask_5](https://github.com/user-attachments/assets/b4e19b31-7b72-47e7-9030-a54c18998aa6)
![Symbolic_mask_2](https://github.com/user-attachments/assets/48927b03-6952-49f0-a8fd-a436aacda621)
![Symbolic_mask_1](https://github.com/user-attachments/assets/c68eeb8e-4077-4ba8-8fa1-b31ca356704e)

**Comment by Han-Yuan-Med** [comment]
I also add some of the other templates for your reference. You can adjust them using different morphological operation techniques such as dilation.
![Mask_1 (2)](https://github.com/user-attachments/assets/6db0dca5-91f7-4e21-a641-7a02411d09fb)
![Mask_1 (4)](https://github.com/user-attachments/assets/607db8c8-0ddd-49dc-b997-05246ad9bc73)
![Mask_1 (1)](https://github.com/user-attachments/assets/b1b99eca-5bbd-4d40-9400-e3d9ddbe4e51)
![Mask_1 (3)](https://github.com/user-attachments/assets/6c44dacc-776c-402e-b249-9a7efeaf6432)
